version: '3.7'

services:
    labelsync:
        build:
            context: ../
            dockerfile: $PWD/LabelSync/Dockerfile
        network_mode: host
        ports:
           - "${LABELSYNC_SERVICE_PORT}:8080"
        depends_on:
            - db_labelsync
    db_labelsync:
        image: postgres:11.4
        network_mode: host
        volumes:
            - labelsync_db:/var/lib/postgresql/data
        environment:
            - "POSTGRES_USER:${postgresUser}"
            - "POSTGRES_PASSWORD:${postgresPassword}"
            - "POSTGRES_DB:${postgresDatabase}"
        ports:
            - "${LABELSYNC_DB_PORT}:5432"
    nginx:
        image: nginx:latest
        network_mode: host
        ports:
            - "80:80"
        volumes:
            - "./Nginx/LabelSync.template:/etc/nginx/conf.d/LabelSync.template"
            - "web-root:/var/www/html"
        environment:
            - NGINX_HOST=${serverName}
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/LabelSync.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    nginxSSL:
        image: nginx:latest
        network_mode: host
        ports:
            - "443:443"
        volumes:
            - "./Nginx/LabelSyncSSL.template:/etc/nginx/conf.d/LabelSyncSSL.template"
            - "./Nginx/entrypoint.sh:/app/entrypoint.sh"
            - "/var/log/nginx/:/var/log/nginx/"
            - "certbot-etc:/etc/letsencrypt"
            - "certbot-var:/var/lib/letsencrypt"
        environment:
            - NGINX_HOST=${serverName}
        restart: always
        depends_on:
            - certbot
        command: /bin/sh -c "/app/entrypoint.sh" 
    certbot:
        image: certbot/certbot
        volumes:
            - "./Certbot/entrypoint.sh:/app/entrypoint.sh"
            - "certbot-etc:/etc/letsencrypt"
            - "certbot-var:/var/lib/letsencrypt"
            - "web-root:/var/www/html"
        environment:
            - CONTACT_EMAIL=${contactEmail}
            - CERT_DOMAINS=${certDomains}
        depends_on:
            - nginx
        entrypoint: /bin/sh -c /app/entrypoint.sh
volumes:
        labelsync_db:
        certbot-etc:
        certbot-var:
        web-root:
